config/routes.rb
Rails.application.routes.draw do
  get 'tags/index'
  get 'tags/show'
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret',
     confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' },
     :controllers => { registrations: 'registrations'} 
  resources :posts do
    resources :comments
  end
  resources :details, except: [:index, :destroy, :show]
  devise_scope :user do
    get '/login', to: 'devise/sessions#new'
    get '/signup', to: 'registrations#new'
    post '/login', to: 'devise/sessions#create'
    authenticated :user do
      root 'posts#index'
    end  
    unauthenticated do
      root 'devise/sessions#new'
    end
  end
  resources :users, only: [:show, :index]
  get '/search', to: 'searches#search'
  resources :tags, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user, foreign_key: 'user_id'
    belongs_to :post, foreign_key: 'post_id'
end

app/models/detail.rb
class Detail < ApplicationRecord
    belongs_to :user, foreign_key: 'user_id'
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, length: { minimum:5, maximum:40 }
    validates :body, presence: true, length: { minimum:10, maximum:1500 }
    belongs_to :user, foreign_key: 'user_id'
    has_many :comments
    acts_as_taggable_on :tags
    def self.search(search)  
        where("lower(users.username) LIKE :search OR lower(posts.title) LIKE :search OR lower(posts.body) LIKE :search", search: "%#{search.downcase}%")
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true, length: { minimum:3, maximum:12 }, uniqueness: true
  has_many :posts
  has_one :detail, :dependent => :destroy
  has_many :comments
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configured_permitted_parameters, if: :devise_controller?
    
    protected
    def configured_permitted_parameters 
        devise_parameter_sanitizer.permit(:account_update, keys:[:avatar, :username, :email, :password, :password_confirmation,   :current_password])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all.order('created_at DESC')
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  def create    
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.user_id = current_user.id
    @comment.save
    flash[:success] = "Comment created successfuly"
    redirect_to post_path (@comment.post) 
  end
  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :edit, :update]

    def new 
        @user = current_user
        @detail = Detail.new(user_id: @user.id)
        @user.detail = @detail
    end

    def create
        @detail = Detail.create(details_params)
    end

    def edit
        @user = current_user
        if @user.detail.nil?
            @detail = Detail.create(user_id: @user.id)
        else
            @detail = Detail.find_by_user_id(params[:id])
        end        
    end

    def update
        @detail = Detail.find(params[:id])
        @detail.update(details_params)
        redirect_to current_user
    end

    private

    def details_params
        params.require(:detail).permit(:nationality, :definition, :employee, :income, :birthdate)
    end

    def set_detail
        @detail = Detail.find(params[:user_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order('created_at DESC')
    @tags = ActsAsTaggableOn::Tag.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
    @comment.post_id = @post.id
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :tag_list)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController 
	
	private

	def sign_up_params 
		params.require(:user).permit(:username, :email, :password, :password_confirmation)
	end

	def account_update_params 
		params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password, :avatar)
	end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    def search 
        if params[:search].blank?
            redirect_to root_path
        else
            @results = Post.joins(:user).search(params[:search])
        end
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @tag =  ActsAsTaggableOn::Tag.find(params[:id])
    @posts = Post.tagged_with(@tag.name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def show
    #@user = User.find_by_username(params[:id])
    #@user = User.find(params[:id])
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def user_avatar (user)
        if user.avatar.attached?
            user.avatar
        else
            'gotham.jpg'
        end
    end
    def full_title(page_title='')
        base_title = "Gotham Blog"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_display.html.erb

<div class="row bootstrap snippets d-flex justify-content-center mt-2 w-100">
    <div class="col-md-6 col-md-offset-2 col-sm-12">
        <div class="comment-wrapper">
            <div class="panel panel-info">
                <div class="panel-heading">
                    Comments
                </div>
                <div class="panel-body">
                    <%= render 'comments/form' %>
                    <div class="panel-heading">
                        This movie has 
                        <%= @post.comments.count %>
                        comments
                    </div>                    
                    <ul class="media-list">
                    <% @post.comments.each do |comment| %>
                        <li class="media">
                            <div class="media-body">
                                <span class="text-muted pull-right">
                                    <small class="text-muted"><%= comment.created_at %></small>
                                </span>
                                <strong class="text-success"><%= comment.user.username %></strong>
                                <p>
                                    <%= comment.content %>.
                                </p>
                            </div>
                        </li>
                    <% end %>                            
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for [@post, @comment] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :content, wrapper: false, label_html: { class:"form-control" }, required: false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-success"  %>
  </div>
<% end %>
<br>
<div class="clearfix"></div>
<hr>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.user_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/details/_form.html.erb
<div class="container">    
            
    <div id="signupbox" style=" margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-info">
            <div class="panel-heading">
                <div class="panel-title">Edit Personal Information</div>
            </div>  
            <div class="panel-body" >
                            

                    <%= simple_form_for @user.detail, defaults: { input_html: { class: 'w-50, input-md  textinput textInput ' } } do |f| %>
                        <div id="div_id_username" class="form-group">
                            <label for="id_username" class="control-label col-md-4  requiredField"> Nationality<span class="asteriskField">*</span> </label>
                            <div class="controls col-md-8 ">
                                <%= f.input :nationality, wrapper: false, label: false, required: false %>
                            </div>
                        </div>
                        <div id="div_id_name" class="form-group"> 
                            <label for="id_name" class="control-label col-md-4  requiredField"> Definition<span class="asteriskField">*</span> </label> 
                            <div class="controls col-md-8 "> 
                                <%= f.input :definition, wrapper: false, label: false, required: false  %>
                            </div>
                        </div>
                        <div id="div_id_name" class="form-group"> 
                            <label for="id_name" class="control-label col-md-4  requiredField"> Birthdate<span class="asteriskField">*</span> </label> 
                            <div class="controls col-md-8 "> 
                                <%= f.input :birthdate, as: :date, start_year: Date.today.year - 90,
                                                            end_year: Date.today.year - 12, order: [:day, :month, :year], wrapper: false,
                                                            label: false, required: false  %>
                            </div>
                        </div>
                        <div id="div_id_employee" class="form-group">
                            <label for="id_employee"  class="control-label col-md-4  requiredField"> Employee<span class="asteriskField">*</span> </label>
                            <div class="controls col-md-8 "  style="margin-bottom: 10px">
                                 <label class="radio-inline"> <input type="radio" name="detail[employee]" value="1"  style="margin-bottom: 10px">Yes</label>
                                 <label class="radio-inline"> <input type="radio" name="detail[employee]" value="0"  style="margin-bottom: 10px">No </label>
                            </div>
                        </div>
                        <div id="div_id_number" class="form-group">
                             <label for="id_number" class="control-label col-md-4  requiredField"> Income<span class="asteriskField">*</span> </label>
                             <div class="controls col-md-8 ">
                                 <%= f.input :income, as: :decimal, wrapper: false, label: false, required: false  %>
                            </div> 
                        </div>
                        <br> 
                        <br>
                        <div class="form-group mt-5"> 
                            <div class="aab controls col-md-4  mt-5"></div>
                            <div class="controls col-md-8 mt-5">
                                <%= f.button :submit, 'Update', class:"btn btn-success" %>
                            </div>
                        </div>                            
                    <% end %>
            </div>
        </div>
    </div> 
</div>
</div>  

app/views/details/edit.html.erb
<div class="container">
<div class="w-50" style="margin: 0 auto;">
<h2>Edit Personal Information</h2>
<br>
<%= render 'form' %>
<br>
<%= link_to 'User profile', current_user,  class:"btn btn-success" %>
<br>
<br>

</div>
</div>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small blue-grey lighten-5">

  <div style="background-color: rgb(0,51,0);">
    <div class="container">

      <!-- Grid row-->
      <div class="row py-4 d-flex align-items-center">

        <!-- Grid column -->
        <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">
          <h6 class="mb-0">Get connected with us on social networks!</h6>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-6 col-lg-7 text-center text-md-right">

          <!-- Facebook -->
          <a class="fb-ic" href="#!">
            <i class="fab fa-facebook-f white-text mr-4"> </i>
          </a>
          <!-- Twitter -->
          <a class="tw-ic" href="#!">
            <i class="fab fa-twitter white-text mr-4"> </i>
          </a>
          <!-- Google +-->
          <a class="gplus-ic" href="#!">
            <i class="fab fa-google-plus-g white-text mr-4"> </i>
          </a>
          <!--Linkedin -->
          <a class="li-ic" href="#!">
            <i class="fab fa-linkedin-in white-text mr-4"> </i>
          </a>
          <!--Instagram-->
          <a class="ins-ic" href="#!">
            <i class="fab fa-instagram white-text"> </i>
          </a>

        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row-->

    </div>
  </div>

  <!-- Footer Links -->
  <div class="container text-center text-md-left mt-5">

    <!-- Grid row -->
    <div class="row mt-3 dark-grey-text">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-4 col-xl-3 mb-4">

        <!-- Content -->
        <h6 class="text-uppercase font-weight-bold">Blog Corp.</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>Lorem ipsum dolor sit amet,
          consectetur
          adipisicing elit.</p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Other Sites</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a class="dark-grey-text" href="#!">Movies App</a>
        </p>
        <p>
          <a class="dark-grey-text" href="#!">Management Users</a>
        </p>
        <p>
          <a class="dark-grey-text" href="#!">Scraper World</a>
        </p>
        <p>
          <a class="dark-grey-text" href="#!">Old School Games</a>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Useful links</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a class="dark-grey-text" href="#!">Your Account</a>
        </p>
        <p>
          <a class="dark-grey-text" href="#!">About</a>
        </p>
        <p>
          <a class="dark-grey-text" href="#!">Partners</a>
        </p>
        <p>
          <a class="dark-grey-text" href="#!">Help</a>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Contact</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <i class="fas fa-home mr-3"></i> Hanoi, HN 100001, VN</p>
        <p>
          <i class="fas fa-envelope mr-3"></i> info@example.com</p>
        <p>
          <i class="fas fa-phone mr-3"></i> + 84 234 567 88</p>
        <p>
          <i class="fas fa-print mr-3"></i> + 84 234 567 89</p>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center text-black-50 py-3">© 2020 Copyright:
    <a class="dark-grey-text" href="#"> BlogCorp.org</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/layouts/_header.html.erb

<header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="./" class="navbar-brand">Blog</a>
    </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav navbar-right">
        <li class="nav-item active">
            <%= link_to 'Home', root_path, class:"nav-link" %>          
        </li>
        <% if current_user.nil? %>
          <li class="nav-item active">
            <%= link_to 'Signup', new_user_registration_path, class:"nav-link" %>            
          </li>
          <li class="nav-item">
            <%= link_to 'Login', new_user_session_path, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to current_user, class:"nav-link" do %>
              <%= current_user.username %>
              <%= image_tag(user_avatar(current_user), size: "25", class:'rounded-circle') %>  
            <% end %>          
          </li>
          <li class="nav-item">
            <%= link_to 'New Post', new_post_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/d4de0f4540.js" crossorigin="anonymous"></script>    
  </head>

  <body>
  <%= render 'layouts/header'%>
   <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type} text-center") %>
  <% end %>

    <%= yield %>


  <%= render 'layouts/footer' %>




  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body, as: :text %>
    <%= f.input :tag_list, placeholder: 'tag1, tag2' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-success" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<% provide(:title, "Edit Post") %>
<div class="container">

<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post, class:"btn btn-success" %>
<%= link_to 'Back to Home', posts_path, class:"btn btn-success" %>

</div>

app/views/posts/new.html.erb
<% provide(:title, "New Post") %>
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% provide(:title, "Post") %>
<p id="notice"><%= notice %></p>
<div class="container">
<div class="card mb-4">
<% if false %><%= image_tag ('gotham.jpg'),  class:"card-img-top", alt:"Gotham city" %><% end %>
          <div class="card-body">
            <h2 class="card-title"><%= @post.title %></h2>
            <p class="card-text"><%= @post.body %></p>
            <% @post.tag_list.each do |tag| %>
              <p class="card-text"><%= link_to tag, tag_path(ActsAsTaggableOn::Tag.find_by_name(tag)) %></p>
            <% end %>
            <%= link_to 'Edit', edit_post_path(@post), class:"btn btn-success" %>
          </div>
          <div class="card-footer text-muted">
            Posted on <%= @post.created_at %> By 
            <a href="#"><%= @post.user.username %></a>
          </div>
</div>


<%= render 'comments/display'%>

<%= link_to 'Back', posts_path, class:"btn btn-success" %>
</div>

app/views/searches/_form.html.erb
<% if false %>
<!-- <form action="/search" method="post" class="form-inline">
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <input class="form-control" name="search" type="search" placeholder="Search for..." aria-label="Search">
                <span class="input-group-btn">
                  <button class="btn btn-outline-secondary" type="submit">Go!</button> 
                </span>
</form> -->
<%= simple_form_for search_path, method: :get do |f| %>
  <%= f.input :search, as: :search, class:"form-control", placeholder: "Search for...", label: false %>
  <%= f.button :submit, 'Search!', class:"btn btn-success glyphicon glyphicon-search" %>
<% end %>
<% end %>


<%= form_tag(search_path, :method => "get",   
    class: 'navbar-form navbar-left') do %>  
  <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Search for...", class: "form-control" %>  
    <div class="input-group-btn">  
      <%= button_tag "", :class => 'btn btn-success glyphicon glyphicon-search',:name => nil %>  
    </div>  
  </div>  
<% end %>




app/views/tags/_tags.html.erb
<div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <%= link_to @tags.sample.name, tag_path(ActsAsTaggableOn::Tag.find_by_name(@tags.sample.name)) %>
                  </li>
                  <li>
                    <%= link_to @tags.sample.name, tag_path(ActsAsTaggableOn::Tag.find_by_name(@tags.sample.name)) %>
                  </li>
                  <li>
                    <%= link_to @tags.sample.name, tag_path(ActsAsTaggableOn::Tag.find_by_name(@tags.sample.name)) %>
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <%= link_to @tags.sample.name, tag_path(ActsAsTaggableOn::Tag.find_by_name(@tags.sample.name)) %>
                  </li>
                  <li>
                    <%= link_to @tags.sample.name, tag_path(ActsAsTaggableOn::Tag.find_by_name(@tags.sample.name)) %>
                  </li>
                  <li>
                    <%= link_to @tags.sample.name, tag_path(ActsAsTaggableOn::Tag.find_by_name(@tags.sample.name)) %>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

app/views/tags/index.html.erb
<% provide(:title, "Tags") %>
<h1>Tags</h1>
<ul>
 <% @tags.each do |tag| %>
    <li><%= link_to tag.name, tag_path(tag) %></li>
 <% end %>
 </ul>

app/views/tags/show.html.erb
<% provide(:title, "Tags") %>
<h1><%= @tag.name %></h1>
<ul>
<% @posts.each do |post| %>
    <li><%= link_to post.title, post_path(post) %></li>
<% end %>
</ul>

app/views/users/show.html.erb
<% provide(:title, "Profile") %>
<br>
<br>
<div class="container">
<div class="containertext-center">
    <div class="card" style="width: 22rem; margin: 0 auto;">
        <%= image_tag(user_avatar(current_user), size: "90!", class:'rounded-circle') %>
    <div class="card-body">
        <h2 class="card-title"><%= current_user.username%> Profile</h2>
        <% if !current_user.detail.nil? %>
        <p class="card-text"><%= current_user.detail.definition %></p>
        <p class="card-text">Nationality: <%= current_user.detail.nationality %></p>
        <p class="card-text">Birthdate: <%= current_user.detail.birthdate %></p>
        <p class="card-text">Income: <%= current_user.detail.income %></p>
        <p class="card-text">Employee: <%= current_user.detail.employee %></p>
        <% end %>
        <%= link_to 'Personal information', edit_detail_path(current_user), class:"btn btn-success" %>
        <%= link_to 'Edit account', edit_user_registration_path, class:"btn btn-success" %>
    </div>
    </div>
</div>
</div>
<br>
<br><br>